name: Hello World

on:
  push:
    branches: [main]

jobs:
  say-hello:
    runs-on: windows-latest

    steps:
      - name: Say Hello
        run: echo "Hello, World!"
      - name: Show the Date
        run: echo today is %DATE%
      - name: Echo today's date
        run: echo "Today is $(date)"
