name: Hello World

on:
  push:
    branches: [main]

jobs:
  say-hello:
    runs-on: windows-latest

    steps:
      - name: Say Hello
        run: echo "Hello, World!"
      - name: Show the Date
        run: echo Today is $(date)
      - name: Show which folder we in
        run: echo Current directory: $(pwd)
